//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mesajlaşma_Platformu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alicilar
    {
        public int id { get; set; }
        public int mesajId { get; set; }
        public int aliciId { get; set; }
    
        public virtual Mesaj Mesaj { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
