//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mesajlaşma_Platformu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MesajlasmaPlatformuEntities : DbContext
    {
        public MesajlasmaPlatformuEntities()
            : base("name=MesajlasmaPlatformuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alicilar> Alicilar { get; set; }
        public virtual DbSet<Grup> Grup { get; set; }
        public virtual DbSet<GrupUye> GrupUye { get; set; }
        public virtual DbSet<Mesaj> Mesaj { get; set; }
        public virtual DbSet<Uye> Uye { get; set; }
    }
}
